/**
 * BLOONS WORLD — the block table.
 *
 * One entry per kind of block, and every question anything in the game asks about a
 * block is answered from here: can you walk through it, does light get past it, how
 * long does it take to dig, what are you holding afterwards, how much does it hurt to
 * land on, and which texture goes on which face.
 *
 * It is shared because both ends need all of it, and they need the SAME all of it.
 * The server decides whether a dig was fast enough to be real and what it dropped;
 * the client decides how long to keep the mouse down and what to draw. Two tables
 * would eventually be two answers, and the one thing worse than a wrong world is two
 * clients that each think the other one is wrong.
 *
 * IDS ARE APPENDED, NEVER REORDERED. A saved world is a list of [position, id] pairs,
 * so renumbering these turns everybody's house into a different house. New blocks go
 * on the end. The save file also carries the id→name table it was written with, so
 * even a reordering could be migrated — but not reordering is free and migrating is
 * not.
 */

// ---------------------------------------------------------------------------
// Textures
//
// Every texture is one layer of a 2D ARRAY texture rather than a tile in an atlas.
// An atlas is the traditional answer and it is the wrong one here: with mipmaps on,
// bilinear filtering at a tile's edge samples the tile NEXT to it, so every distant
// block gets a one-pixel rind of its neighbour's colour. An array texture has no
// neighbours to bleed from — each layer is its own image, wrapped on its own — and
// the vertex just carries which layer to use.

export const TEX = {
  stone: 0,
  dirt: 1,
  grassTop: 2,
  grassSide: 3,
  sand: 4,
  gravel: 5,
  cobble: 6,
  logSide: 7,
  logTop: 8,
  leaves: 9,
  planks: 10,
  glass: 11,
  coalOre: 12,
  ironOre: 13,
  goldOre: 14,
  diamondOre: 15,
  lamp: 16,
  brick: 17,
  water: 18,
  bedrock: 19,
  tallGrass: 20,
  flower: 21,
  sandstoneTop: 22,
  sandstoneSide: 23,
  ironBlock: 24,
  goldBlock: 25,
  diamondBlock: 26,
  mossy: 27,
  thatch: 28,
  // Things lying on the ground that you pick up rather than mine.
  pebbles: 29,
  sticks: 30,
  berryBush: 31,
  mushroom: 32,
  // Item icons. Flat pictures rather than cube faces — a pickaxe is not a cube.
  itemPebble: 33,
  itemStick: 34,
  itemBerries: 35,
  itemRoot: 36,
  itemMushroom: 37,
  itemCoal: 38,
  itemIron: 39,
  itemGold: 40,
  itemDiamond: 41,
  /*
   * Twelve tools: three kinds by four materials, laid out so the material is the
   * offset. `itemPick + tier` is the pickaxe for that tier, which is what lets the
   * whole set be generated by one function with a colour rather than drawn twelve
   * times.
   */
  itemPick: 42,
  itemAxe: 46,
  itemShovel: 50,
  furnaceFront: 54,
  furnaceSide: 55,
  furnaceTop: 56,
  // The two things you cannot make a gun without, and the gun.
  sulfurOre: 57,
  nitreOre: 58,
  itemSulfur: 59,
  itemNitre: 60,
  itemPowder: 61,
  itemShot: 62,
  itemMusket: 63,
  itemRifle: 64,
  itemBall: 65,
  itemCartridge: 66,
  itemRevolver: 67,
  itemAutoRifle: 68,
  itemMachineGun: 69,
  ladder: 80,
  itemMeat: 83,
  itemCooked: 84,
  sapling: 85,
  /** Ten stages of cracking, `crack + 0` through `crack + 9`. Kept last on purpose. */
  crack: 70,
} as const;

export const CRACK_STAGES = 10;
/** How many layers the array texture has. Everything above must fit under this. */
export const TEX_LAYERS = 88;

// ---------------------------------------------------------------------------
// The blocks themselves

export const AIR = 0;
export const BEDROCK = 1;
export const STONE = 2;
export const DIRT = 3;
export const GRASS = 4;
export const SAND = 5;
export const GRAVEL = 6;
export const COBBLE = 7;
export const LOG = 8;
export const LEAVES = 9;
export const PLANKS = 10;
export const GLASS = 11;
export const COAL_ORE = 12;
export const IRON_ORE = 13;
export const GOLD_ORE = 14;
export const DIAMOND_ORE = 15;
export const LAMP = 16;
export const BRICK = 17;
export const WATER = 18;
export const TALL_GRASS = 19;
export const FLOWER = 20;
// --- everything below here can only be made, never found.
export const SANDSTONE = 21;
export const IRON_BLOCK = 22;
export const GOLD_BLOCK = 23;
export const DIAMOND_BLOCK = 24;
export const MOSSY_COBBLE = 25;
export const THATCH = 26;
/**
 * Slabs and stairs, four materials each.
 *
 * A stair takes FOUR ids, one per direction it faces, because the world is one byte
 * per cell and there is nowhere to write a rotation. `STAIRS_X` is the first of the
 * four and the others follow it, so `STAIRS_X + facing` is the whole of the lookup.
 */
export const COBBLE_SLAB = 34;
export const COBBLE_STAIRS = 35; // …36, 37, 38
export const PLANK_SLAB = 39;
export const PLANK_STAIRS = 40; // …41, 42, 43
export const BRICK_SLAB = 44;
export const BRICK_STAIRS = 45; // …46, 47, 48
export const SANDSTONE_SLAB = 49;
export const SANDSTONE_STAIRS = 50; // …51, 52, 53

/**
 * A ladder, on one of four walls. `LADDER + facing` is the whole lookup.
 *
 * Facing here means WHICH WALL IT IS NAILED TO, not which way it looks — a ladder on
 * the east wall of a shaft faces west, and describing it the other way round means
 * getting the sign wrong every single time you touch it.
 */
export const LADDER = 54; // …55, 56, 57
/** Drops from leaves, grows back into a tree if you plant it and wait. */
export const SAPLING = 58;

// --- things lying about, picked up by hand.
export const PEBBLES = 27;
export const STICKS = 28;
export const BERRY_BUSH = 29;
export const MUSHROOM = 30;
/** Put one down and you can smelt beside it. Eight cobble. */
export const FURNACE = 31;
/** The two halves of black powder, both of them deep and both of them rare. */
export const SULFUR_ORE = 32;
export const NITRE_ORE = 33;

/**
 * How a block is put on the screen.
 *
 *  - `cube`  the ordinary case: six faces, and any face touching something solid is
 *            never built in the first place.
 *  - `cross` two quads in an X, which is how every game has drawn grass and flowers
 *            since it stopped being able to afford geometry. Drawn from both sides.
 *  - `none`  air. Nothing at all.
 */
export type Shape = 'cube' | 'cross' | 'none' | 'slab' | 'stair' | 'ladder';

/**
 * The boxes a block actually occupies, in block-local 0..1.
 *
 * A full cube is one box and needs no entry. A slab is the bottom half. Stairs are a
 * slab with a quarter sitting on the back of it, and which side is "back" is the four
 * separate block ids — the world is a byte per cell with no room for a rotation, and
 * a parallel array of orientations would be another megabyte and another thing to
 * keep in step on the wire. Four ids is free.
 *
 * These are used for BOTH the collision and the mesh, which is the only way the thing
 * you can see and the thing you bump into stay the same shape.
 */
export type Box = [number, number, number, number, number, number];

const FULL: Box[] = [[0, 0, 0, 1, 1, 1]];
const SLAB: Box[] = [[0, 0, 0, 1, 0.5, 1]];

/** Stairs: the lower slab, plus the upper step against one side. */
function stairBoxes(facing: number): Box[] {
  const step: Box =
    facing === 0 ? [0.5, 0.5, 0, 1, 1, 1] :
    facing === 1 ? [0, 0.5, 0.5, 1, 1, 1] :
    facing === 2 ? [0, 0.5, 0, 0.5, 1, 1] :
    [0, 0.5, 0, 1, 1, 0.5];
  return [[0, 0, 0, 1, 0.5, 1], step];
}

/**
 * Which of the four stair ids to actually place, given where somebody is looking.
 *
 * The step goes on the FAR side, so walking the way you were facing takes you up it.
 * That is what everybody expects and nobody could tell you they expect: laid the
 * other way a staircase is a wall you have to jump, and it is not obvious why until
 * you turn round.
 */
export function orientFor(block: number, yaw: number): number {
  const def = blockDef(block);
  if (def.shape !== 'stair') return block;
  const quarter = ((Math.round(yaw / (Math.PI / 2)) % 4) + 4) % 4;
  return block - def.facing + quarter;
}

export function boxesOf(block: number): Box[] {
  const def = blockDef(block);
  if (def.shape === 'slab') return SLAB;
  if (def.shape === 'stair') return stairBoxes(def.facing);
  return FULL;
}

/** The four walls a ladder can hang on, as the direction from the ladder TO the wall. */
export const WALL_DIRS: [number, number, number][] = [
  [1, 0, 0],
  [0, 0, 1],
  [-1, 0, 0],
  [0, 0, -1],
];

/**
 * Which ladder id to place, from the face that was clicked.
 *
 * The block goes in the empty cell next to the wall, so the wall is in the OPPOSITE
 * direction from the face normal. Returns null for a floor or a ceiling: a ladder
 * needs something to be nailed to, and one lying flat on the ground would be a
 * texture rather than a way up.
 */
export function ladderFor(nx: number, ny: number, nz: number): number | null {
  if (ny !== 0) return null;
  for (let f = 0; f < 4; f++) {
    const [wx, , wz] = WALL_DIRS[f];
    if (wx === -nx && wz === -nz) return LADDER + f;
  }
  return null;
}

/**
 * Which tool family a block yields to. Declared here rather than imported from
 * `items.ts` because items import THIS file — a block has to be able to say what it
 * needs without knowing what an axe is.
 */
export type ToolKind = 'none' | 'axe' | 'pick' | 'shovel' | 'blade';

export interface BlockDef {
  id: number;
  /** What the hotbar calls it. Also the key a saved world is migrated by. */
  name: string;
  /** Texture layers: [top, bottom, side]. */
  tex: [number, number, number];
  shape: Shape;
  /** Stops a body. */
  solid: boolean;
  /** Fills its cell for the purposes of hiding the faces behind it. */
  opaque: boolean;
  /** You swim in it rather than standing on it. */
  liquid: boolean;
  /** Placing something here overwrites it instead of landing beside it. */
  replaceable: boolean;
  /** Light levels eaten per block. 15 is "none gets through". */
  opacity: number;
  /** Light given off, 0..15. */
  glow: number;
  /** Seconds of digging with bare hands. `Infinity` means never. */
  hardness: number;
  /**
   * Which tool this yields to, and the lowest tier that can touch it AT ALL.
   *
   * Tier 0 is the ordinary case and means BARE HANDS WORK — the right tool is simply
   * faster. You punch a tree and you get wood, the same way you always have; an axe
   * just does it in a third of the time.
   *
   * Tier 1 and up is a real wall: stone needs a pickaxe, iron ore needs a stone
   * pickaxe, diamond needs an iron one. That is not a gate somebody invented, it is
   * the shape of the game — and it is the only kind of gate here.
   */
  tool: ToolKind;
  tier: number;
  /** For stairs: 0 = the step is on the +x side, then +z, -x, -z. */
  facing: number;
  /**
   * How much of a fall this block passes on to whoever lands on it, 0..1.
   *
   * Stone is 1 and is the reference. Sand is 0.08 — you can drop off the top of the
   * world onto a beach and lose about half a heart — because a beach SHOULD be the
   * safe way down, and because a game where the ground is uniformly hostile teaches
   * you nothing about where to land. See `fallDamage`.
   */
  softness: number;
}

function def(id: number, name: string, tex: number | [number, number, number], extra: Partial<BlockDef> = {}): BlockDef {
  const t: [number, number, number] = typeof tex === 'number' ? [tex, tex, tex] : tex;
  return {
    id,
    name,
    tex: t,
    shape: 'cube',
    solid: true,
    opaque: true,
    liquid: false,
    replaceable: false,
    opacity: 15,
    glow: 0,
    hardness: 1,
    tool: 'pick',
    tier: 0,
    facing: 0,
    softness: 1,
    ...extra,
  };
}

/**
 * Every block, in whatever order reads best. NOT the lookup table — see below.
 */
const AUTHORED: BlockDef[] = [
  def(AIR, 'air', 0, {
    shape: 'none',
    solid: false,
    opaque: false,
    replaceable: true,
    opacity: 0,
    hardness: Infinity,
    tool: 'none',
  }),
  // The floor of the world. Deliberately impossible to dig: the bottom of a voxel
  // world has to be somewhere, and a hole you can fall out of the universe through
  // is a bug report rather than a feature.
  def(BEDROCK, 'bedrock', TEX.bedrock, { hardness: Infinity }),

  // --- soil, and everything else your hands can move. A shovel is three times
  // faster and is never required.
  def(DIRT, 'dirt', TEX.dirt, { hardness: 0.75, tool: 'shovel', softness: 0.8 }),
  def(GRASS, 'grass', [TEX.grassTop, TEX.dirt, TEX.grassSide], {
    hardness: 0.9, tool: 'shovel', softness: 0.8,
  }),
  def(SAND, 'sand', TEX.sand, { hardness: 0.75, tool: 'shovel', softness: 0.08 }),
  def(GRAVEL, 'gravel', TEX.gravel, { hardness: 0.9, tool: 'shovel', softness: 0.55 }),

  // --- wood. Punch it. An axe is faster and that is the only difference.
  def(LOG, 'log', [TEX.logTop, TEX.logTop, TEX.logSide], {
    hardness: 3.0, tool: 'axe', softness: 0.85,
  }),
  def(PLANKS, 'planks', TEX.planks, { hardness: 2.4, tool: 'axe', softness: 0.85 }),
  def(LEAVES, 'leaves', TEX.leaves, {
    opaque: false, opacity: 1, hardness: 0.3, tool: 'none', softness: 0.18,
  }),

  /*
   * --- rock, and the one real wall in the game.
   *
   * A pickaxe or nothing, and a better pickaxe for better rock: wood reaches stone
   * and coal, stone reaches iron, iron reaches gold and diamond. Every one of those
   * numbers is Minecraft's, because that ladder is the single best-tuned thing in it —
   * each tier is exactly one trip underground away from the next.
   */
  def(STONE, 'stone', TEX.stone, { hardness: 4.5, tool: 'pick', tier: 1 }),
  def(COBBLE, 'cobble', TEX.cobble, { hardness: 4.5, tool: 'pick', tier: 1 }),
  def(COAL_ORE, 'coal ore', TEX.coalOre, { hardness: 5.5, tool: 'pick', tier: 1 }),
  def(IRON_ORE, 'iron ore', TEX.ironOre, { hardness: 6.5, tool: 'pick', tier: 2 }),
  def(GOLD_ORE, 'gold ore', TEX.goldOre, { hardness: 6.5, tool: 'pick', tier: 3 }),
  def(DIAMOND_ORE, 'diamond ore', TEX.diamondOre, { hardness: 7.5, tool: 'pick', tier: 3 }),

  def(GLASS, 'glass', TEX.glass, { opaque: false, opacity: 0, hardness: 0.4, tool: 'none' }),
  def(LAMP, 'lamp', TEX.lamp, { glow: 14, hardness: 0.4, tool: 'none' }),
  def(BRICK, 'brick', TEX.brick, { hardness: 4.5, tool: 'pick', tier: 1 }),
  def(FURNACE, 'furnace', [TEX.furnaceTop, TEX.furnaceTop, TEX.furnaceSide], {
    hardness: 5.0, tool: 'pick', tier: 1,
  }),
  def(WATER, 'water', TEX.water, {
    solid: false,
    opaque: false,
    liquid: true,
    replaceable: true,
    // Two levels a block, so a deep lake is dim at the bottom and a puddle is not.
    opacity: 2,
    hardness: Infinity,
    tool: 'none',
  }),

  // --- things growing, and things lying about. All free, all by hand.
  def(TALL_GRASS, 'tall grass', TEX.tallGrass, {
    shape: 'cross', solid: false, opaque: false, replaceable: true,
    opacity: 0, hardness: 0, tool: 'none',
  }),
  def(FLOWER, 'flower', TEX.flower, {
    shape: 'cross', solid: false, opaque: false, replaceable: true,
    opacity: 0, hardness: 0, tool: 'none',
  }),
  def(PEBBLES, 'pebbles', TEX.pebbles, {
    shape: 'cross', solid: false, opaque: false, replaceable: true,
    opacity: 0, hardness: 0, tool: 'none',
  }),
  def(STICKS, 'fallen sticks', TEX.sticks, {
    shape: 'cross', solid: false, opaque: false, replaceable: true,
    opacity: 0, hardness: 0, tool: 'none',
  }),
  def(BERRY_BUSH, 'berry bush', TEX.berryBush, {
    shape: 'cross', solid: false, opaque: false, replaceable: true,
    opacity: 0, hardness: 0, tool: 'none',
  }),
  def(MUSHROOM, 'mushroom', TEX.mushroom, {
    shape: 'cross', solid: false, opaque: false, replaceable: true,
    opacity: 0, hardness: 0, tool: 'none',
  }),

  // --- made, never found.
  def(SANDSTONE, 'sandstone', [TEX.sandstoneTop, TEX.sandstoneTop, TEX.sandstoneSide], {
    hardness: 3.2, tool: 'pick', tier: 1, softness: 0.5,
  }),
  def(IRON_BLOCK, 'iron block', TEX.ironBlock, { hardness: 6.0, tool: 'pick', tier: 2 }),
  def(GOLD_BLOCK, 'gold block', TEX.goldBlock, { hardness: 5.0, tool: 'pick', tier: 3 }),
  def(DIAMOND_BLOCK, 'diamond block', TEX.diamondBlock, { hardness: 6.5, tool: 'pick', tier: 3 }),
  def(MOSSY_COBBLE, 'mossy cobble', TEX.mossy, { hardness: 4.5, tool: 'pick', tier: 1, softness: 0.7 }),

  /*
   * Sulfur and nitre. Deep, rare, and worth nothing at all on their own — which is
   * the point of them: the only reason to want either is that together with coal they
   * are black powder, and black powder is the end of the tree.
   */
  def(SULFUR_ORE, 'sulfur ore', TEX.sulfurOre, { hardness: 6.0, tool: 'pick', tier: 2 }),
  def(NITRE_ORE, 'nitre ore', TEX.nitreOre, { hardness: 6.0, tool: 'pick', tier: 2 }),
  def(THATCH, 'thatch', TEX.thatch, { hardness: 0.5, tool: 'none', softness: 0.03 }),

  // --- stairs and slabs. Half-height and quarter-cut, so a building can have a way
  // up that is not a ladder of jumps.
  ...cutStone(COBBLE_SLAB, COBBLE_STAIRS, 'cobble', TEX.cobble, 4.5, 'pick', 1),
  ...cutStone(PLANK_SLAB, PLANK_STAIRS, 'plank', TEX.planks, 2.4, 'axe', 0),
  ...cutStone(BRICK_SLAB, BRICK_STAIRS, 'brick', TEX.brick, 4.5, 'pick', 1),
  ...cutStone(SANDSTONE_SLAB, SANDSTONE_STAIRS, 'sandstone', TEX.sandstoneSide, 3.2, 'pick', 1),

  /*
   * Ladders. Not solid — you stand INSIDE the cell and hold space to go up — which is
   * the only way a ladder can work in a world made of whole blocks: anything you
   * bumped into would take the shaft it was in from one block wide to none.
   */
  ...ladders(),

  def(SAPLING, 'sapling', TEX.sapling, {
    shape: 'cross', solid: false, opaque: false, replaceable: true,
    opacity: 0, hardness: 0, tool: 'none',
  }),

];

function ladders(): BlockDef[] {
  const WALL = ['east', 'south', 'west', 'north'];
  return WALL.map((wall, f) =>
    def(LADDER + f, `ladder on the ${wall}`, TEX.ladder, {
      shape: 'ladder',
      solid: false,
      opaque: false,
      opacity: 0,
      hardness: 0.4,
      tool: 'none',
      facing: f,
      softness: 0.1,
    }),
  );
}

/** One slab and four stairs in a material. Five ids, one line. */
function cutStone(
  slab: number, stairs: number, name: string, tex: number,
  hardness: number, tool: ToolKind, tier: number,
): BlockDef[] {
  const common = { hardness, tool, tier, opaque: false, opacity: 0 };
  const out = [def(slab, `${name} slab`, tex, { ...common, shape: 'slab' as Shape })];
  const WAY = ['east', 'south', 'west', 'north'];
  for (let f = 0; f < 4; f++) {
    out.push(
      def(stairs + f, `${name} stairs ${WAY[f]}`, tex, { ...common, shape: 'stair' as Shape, facing: f }),
    );
  }
  return out;
}

/**
 * Indexed BY ID, so `BLOCKS[b]` is a plain array lookup on the hot path — this is
 * read once per face per block per remesh, a few million times when the world first
 * appears.
 *
 * Built from the authored list rather than being it, and that is not tidiness. When
 * the two were the same array, reordering the list for readability silently
 * renumbered every block: stone became dirt, iron ore became gold, and the recipe
 * list cheerfully offered "1 leaves -> 4 cobble". Nothing crashed and nothing warned,
 * because every id was still a valid index into something. The check below turns that
 * entire class of mistake into a message at startup.
 */
export const BLOCKS: BlockDef[] = [];
for (const b of AUTHORED) {
  if (BLOCKS[b.id]) throw new Error(`blocks: id ${b.id} is both "${BLOCKS[b.id].name}" and "${b.name}"`);
  BLOCKS[b.id] = b;
}
for (let i = 0; i < BLOCKS.length; i++) {
  if (!BLOCKS[i]) throw new Error(`blocks: nothing has id ${i}, so the table has a hole in it`);
}

/** The block, or air for anything that is not a block. Never throws, never null. */
export function blockDef(id: number): BlockDef {
  return BLOCKS[id] ?? BLOCKS[AIR];
}

/** Every block that can be put back down, in the order the inventory lists them. */
export const PLACEABLE: number[] = BLOCKS.filter(
  (b) => b.id !== AIR && b.id !== WATER && b.id !== BEDROCK,
).map((b) => b.id);

/**
 * Should the face of `self` that looks at `neighbour` be built at all?
 *
 * The ordinary rule is "not if the neighbour fills its cell". The second rule is the
 * one that stops a glass wall from being a stack of visible panes: glass against
 * glass hides both faces, so a window reads as one sheet rather than as the inside
 * of an aquarium. Water does the same against water, or every lake would be a grid.
 */
export function faceVisible(self: number, neighbour: number): boolean {
  const nb = blockDef(neighbour);
  if (nb.opaque) return false;
  if (neighbour === self && (self === GLASS || self === WATER || self === LEAVES)) return false;
  return true;
}

